services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.php
      target: app
    container_name: real_estate_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./storage:/var/www/html/storage:rw
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./public:/var/www/html/public:rw
      - ./.env:/var/www/html/.env
      - ./deploy/logs:/var/log
    networks:
      - realestate_network
    depends_on:
      - mysql
      - real_estate_redis

  # Nginx Web Server
  nginx:
    build:
      context: .  
      dockerfile: dockerfiles/Dockerfile.nginx
    container_name: real_estate_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "${NGINX_PORT:-81}:443"
    volumes:
      - ./public:/var/www/html/public:ro
      - ./storage:/var/www/html/storage:ro
    networks:
      - realestate_network
    depends_on:
      - app

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: real_estate_mysql
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-real_estate}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-asdffdsa}
      MYSQL_USER: ${DB_USERNAME:-real_estate}
      MYSQL_PASSWORD: ${DB_PASSWORD:-asdffdsa}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./deploy/config/mysql/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
    networks:
      - realestate_network
    command: --default-authentication-plugin=mysql_native_password

  real_estate_redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: real_estate_redis
    ports:
      - "6375:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - realestate_network
    command: redis-server --appendonly yes

volumes:
  mysql_data:
    driver: local
  redis_data_dev:
    driver: local

networks:
  realestate_network:
    driver: bridge
  
